CHANGELOG.md, _setup.sh, conjurapi/config.go, docker-compose.yml
To match other client libraries
Happy CI job here - https://jenkins.conjur.net/job/cyberark--conjur-api-go/job/fix%252Fversion-alias/
To test this, export `CONJUR_VERSION=4` and you'll get v4 behavior.
=> Make CONJUR_VERSION an alias for CONJUR_MAJOR_VERSION

conjurapi/config.go, conjurapi/config_test.go
+ support for `version` conjurrc attribute. addresses https://github.com/cyberark/conjur-api-go/issues/18
+ added test for `TestConfig_mergeYAML`
+ see `conjurapi/config.go` and `conjurapi/config_test.go`
https://jenkins.conjur.net/job/cyberark--conjur-api-go/job/version-conjurrc
=> support for `version` conjurrc attribute 

conjurapi/authn/auth_token.go, conjurapi/authn/auth_token_test.go
I came across some issues that caused the AuthToken4 not to be refreshed after the initial token expired.
Firstly, unmarshalling the JSON token was failing on the `timestamp` field. I removed the duplicate string field and implemented the [`Unmarshaler`](https://golang.org/pkg/encoding/json/#Unmarshaler) interface to clean things up.
Second, `FromJSON` is now called from `NewToken` since JSON was being passed in anyway.
Then lastly the `RefreshToken` function was just backwards. I fixed it.
=> Fix AuthToken4 Refresh

_setup.sh, conjurapi/client.go, conjurapi/router_v4.go, conjurapi/router_v5.go, conjurapi/variable.go, conjurapi/variable_test.go
This change exposes the batch secret retrieval endpoint for both V4 and V5. You can access it via the `RetrieveBatchSecrets` method on the `Client` struct.
Tests are included. Run `./test.sh`.
=> Add ability to retrieve batch secrets

conjurapi/policy.go
Add tags to the `PolicyResponse` struct. With these tags, marshaling it will produce a string that matches the server's response.
=> fix JSON keys for PolicyResponse

CHANGELOG.md, conjurapi/client.go, conjurapi/config.go, conjurapi/logging/logging.go, conjurapi/resource.go, conjurapi/resource_test.go, conjurapi/response/error.go, conjurapi/response/response.go, conjurapi/router_url.go, conjurapi/router_v4.go, conjurapi/router_v5.go, docker-compose.yml
This is part of the work required for cyberark/conjur-cli-go#6.
It adds support for fetching all user-visible resources, optionally filtered by `kind`. It also adds support for fetching a single resource by id. In both cases, it unmarshals the JSON into a `map[string]interface{}` for easier examination by the caller. (Eventually, we may want to create structs for each of the resource types.)
I only added support to the v5 router here. It's not clear to me that we should continue to add functionality to the v4 router.
The API now uses an internal instance of a `logrus` logger, setting its destination using the value of the `CONJURAPI_LOG` environment variable.
To review, it's probably best to read the commits individually. Please don't squash merge them -- I worked hard to keep them …
=> add support for fetching resources

CHANGELOG.md, Gopkg.lock, Gopkg.toml, conjurapi/config.go
Upgrade to gopkg.in/yaml.v2, which allows correct marshaling of conjurapi.Config into YAML.
Needed for cyberark/conjur-cli-go#13.
History is clean, no need to squash-merge.
=> Fix marshaling of conjurapi.Config

_setup.sh, conjurapi/authn_test.go, conjurapi/router_v4.go, conjurapi/router_v5.go, conjurapi/variable_test.go
+ add support to v4 router for fully qualified variable ids
+ remove duplicated code by using `parseID`
+ add tests for rotating non-user API key
=> fix: v4 supports fully qualified variable ids

conjurapi/client.go
adding HttpClient public property to Client, so that it can be overridden with Proxy support, custom headers/useragent & GoVCR for testing & http request playback
https://github.com/seborama/govcr
=> Allow overriding http.Client

CHANGELOG.md, conjurapi/config.go
Move the functionality to get the user's home dir out of LoadConfig, and if
the call to user.Current errors, return a blank home dir value
If there is no home dir value set, skip the netrc and conjurrc methods which
use the home dir as the base dir
Ultimately we may want to use a method to retrieve the user's home dir that is
more generally reliable, for example when [os.UserHomeDir](https://github.com/golang/go/issues/26463) is released in Go 1.12
Connected to #39 
[Jenkins build](https://jenkins.conjur.net/job/cyberark--conjur-api-go/job/fix-loadconfig-user-error/)
=> Update LoadConfig to call getHomeDir method

CHANGELOG.md
This will allow people looking at the changelog to see the changes
between 0.6.0 version and the older ones.
=> Added links to the new v0.6.0 release to CHANGELOG

Dockerfile, Jenkinsfile, test.sh
Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
- Adds code to measure code coverage when the tests are run, archive that coverage report in Jenkins and upload the coverage data to Code Climate
Fixes #57
=> Measure coverage when tests run

CHANGELOG.md, conjurapi/config.go, conjurapi/config_test.go
Previously the errors were eaten and no error was thrown but now we do
both so that the user can pinpoint problematic areas quickly.
Resolves #74
=> 74 We now correctly throw errors when `.conjurrc` is unparsable

CHANGELOG.md, conjurapi/client.go, conjurapi/router_v4.go, conjurapi/router_v5.go, conjurapi/variable.go, conjurapi/variable_test.go, docker-compose.yml
Updated the Go client to have an option to use the header `Accept: base64` when making batch secret requests to Conjur. This will automatically encode all secrets in base64 before returning them, which ensures binary secrets do not cause encoding errors in Conjur.
Resolves #88
=> Update secrets batch request

CHANGELOG.md, conjurapi/resource_test.go, conjurapi/router_url.go, conjurapi/router_v5.go
Previously the constructed query string for the Resources method was
additionally passed through fmt.Sprintf, which broke the valid URL-encoding in
the query strings. To resolve this, most methods use a new method
"withFormattedQuery" that continues to leverage Sprintf to interpolate values
into strings, but Resources just appends the query string directly to the URL.
Resolves #93
=> Update resources logic to use the exact query

CHANGELOG.md, conjurapi/router_v5.go
The header parameter used to set secrets to base64 encode
on batch retrieval was changed from Accept to Accept-Encoding
in Conjur, this change reflects that.
Resolves #99
=> Updated the batch secrets retrieval header param

CHANGELOG.md, conjurapi/variable.go
Added a check in the `ReturnBatchSecretsSafe` method which will return an error if the method is used and the proper `Content-Encoding` header is not returned.
=> New error state when conjur cant handle encoding

conjurapi/variable_test.go
Conjur has changed behavior, a failure to encode batch secrets results in a 406 status code instead of the previous 500, se https://github.com/cyberark/conjur/pull/2124.
This PR updates the tests to reflect the new format.
Resolves -
=> Fix tests: Batch retrieval failure now returns 406

bin/start-conjur.sh, bin/test.sh, bin/utils.sh, conjurapi/authn/token_file_authenticator.go, conjurapi/authn/token_file_authenticator_test.go
Fix flaky token authenticator tests. Running `while true; do go test -count=1 -v ./...; done` should result in a sequence of passing tests :)
1. Introduce and use `ensureWriteFile`, a utility function that returns only when the file's modtime has been updated. The guarantees of normal write functions breakdown under unpredictable disk i/o performance (e.g. when running in Docker)... Upon further reflection, I'm not sure these guarantees exist at all when modtime is concerned, see [article](https://www.gnu.org/software/coreutils/manual/html_node/File-timestamps.html#:~:text=For%20efficiency%20reasons,mtimes%20and%20ctimes)
2. Deduplicate COMPOSE_PROJECT_NAME envvar and CLI flag
Resolves #[relevant GitHub issue(s), e.g. 76]
CyberArk internal issue link: [insert issue ID]()
*At least 1 todo …
=> Fix token authenticator tests

CHANGELOG.md, Dockerfile
Updates the base image in the repo Dockerfile to use Go 1.17 in keeping with the earlier upgrade we did. 
Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
=> Update Dockerfile base image to go 1.17

Jenkinsfile
The automatic adjustment of coverage thresholds is currently leading to some
unexpected and inconvenient build failures, often on commits that only include
changes to non-code files. Disable it for now.
=> Disable cobertura ratcheting

CHANGELOG.md, NOTICES.txt, go.mod, go.sum
Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
Remove reference to versions of gopkg.in/yaml.v3 prior to v3.0.1
Update github.com/stretchr/testify to 1.7.2
CyberArk internal issue link: [CONJSE-1377]()
merged.*
changes, or
=> Upgrade stretchr/testify to 1.7.2

.gitlab-ci.yml, CONTRIBUTING.md, Dockerfile, Jenkinsfile, LICENSE, README.md, bin/test.sh, docker-compose.yml
Golang 1.16 support was removed in cyberark/conjur-api-go#121 but remained in the CI. This PR removes it and adds 1.18 as an additional tested version
- Removed support for testing against Golang 1.16
- Removed stated support of Golang 1.16 from README
- Removed CI steps that tested with Golang 1.16
- Added a new CI step that tests with Golang 1.18
- Updated copyright year from 2020 to 2022
N/A
changes, or
=> Remove Golang 1.16 from CI, replace with 1.18

CHANGELOG.md, conjurapi/client.go
Fix bug introduced by #130. Bug reported by @matthiasjung.
In https://github.com/cyberark/conjur-api-go/pull/130 we added support for a new env var for authn-jwt, CONJUR_AUTHN_JWT_HOST_ID. We used an if statement to check whether this env var was set, but we seem to have accidentally switched what should have been an `if authnJwtHostID != ""` => _consume variable_ to instead say `if authnJwtHostID == ""` => _consume variable__, which makes no sense.
There are no unit tests on the `NewClientFromEnvironment` function. These should ideally be added but should not delay this bug fix.
changes, or
=> Fix bug with JWT env var

conjurapi/client.go, conjurapi/client_test.go
*To fix the issue open in https://github.com/cyberark/terraform-provider-conjur/issues related to support authentication using access token issue
*accessTokenFile variable used instead of accessToken : client.go
*test case added in client_test.go
Resolves #[https://github.com/cyberark/terraform-provider-conjur/issues/69
https://github.com/cyberark/terraform-provider-conjur/issues/99
]
* 'CONJUR_AUTHN_TOKEN' : support for access token added for Terraform provider Conjur 
changes, or
=> Access token change

conjurapi/client.go, conjurapi/resource.go, conjurapi/resource_test.go
This pull request adds an API endpoint for 'resource permitted-roles' for the Conjur CLI - Golang version.
- Added API endpoint for 'permitted-roles'
- Added tests for API endpoint
merged.*
changes, or
=> Implements resource permitted-roles command in API

CHANGELOG.md, conjurapi/authn.go, conjurapi/authn/oidc_authenticator.go, conjurapi/authn_test.go, conjurapi/client.go, conjurapi/client_test.go, conjurapi/config.go, conjurapi/config_test.go
Add support for authn-oidc in the Conjur Golang API
- Support the List OIDC Providers endpoint ([Docs](https://docs.conjur.org/Latest/en/Content/Developer/Conjur_API_List_OIDC_Providers.htm))
- Support the OIDC authentication (V2) endpoint ([Docs](https://docs.conjur.org/Latest/en/Content/Developer/Conjur_API_OIDC_Authenticator.htm#OIDCAuthenticatorforConjurUIauthentication))
CyberArk internal issue ID: ONYX-25484
changes, or
=> OIDC support

conjurapi/authn.go, conjurapi/authn_test.go, conjurapi/config.go
Make the DefaultOidcTokenPath variable public so consuming packages (such as the CLI) can consume it.
changes, or
=> Make DefaultOidcTokenPath public

conjurapi/authn.go, conjurapi/authn_test.go, conjurapi/client.go, conjurapi/config.go, conjurapi/logging/logging.go, conjurapi/storage.go, conjurapi/storage_test.go
Until now the storage of Conjur credentials in the user's .netrc file was handled in the CLI repo. This PR moves it all to the API repo. There are (at least) three major advantages to this.
1. It can be used by summon-conjur or any other client that uses the API.
2. We can store the access token, which we use when using authn-oidc, in the .netrc just as we do with the api key for authn.
3. We can easily add other storage mechanisms (such as native system keystores) that will work with all clients of the API.
- Moved the storage functions from the CLI repo to the API repo
- Modified the storage of the access token, used in authn-oidc, to use the same functions as the api key storage which is used in authn and authn-ldap.
- Added a config option (not saved in conjurrc) that allows clients …
=> Move credentials storage logic to API

conjurapi/host_factory.go, conjurapi/host_factory_test.go
The CreateHost API should just take the id string and format it correctly.
MAde CreateHost a wrapper to createHost to take the id as an arg.
CyberArk internal issue ID: [ONYX-26890]
merged.*
changes, or
=> Update CreateHost API

CHANGELOG.md, README.md, conjurapi/client.go
The desired outcome of this PR is to add support for authenticating using authn-jwt through the conjur-api-go SDK where the token is provided as a raw value rather than being located in a file at a particular path that can be read.
*Describe how the desired outcome above has been achieved with this PR. In
particular, consider:*
- _What's changed? Why were these changes made?_
This PR adds a new environment variable called `CONJUR_AUTHN_JWT_TOKEN` that, when present, overrides the requirement to provide `CONJUR_TOKEN_PATH`.  If the `CONJUR_AUTHN_JWT_TOKEN` is not present, `CONJUR_TOKEN_PATH` is assumed and the typical logic established prior to this PR still applies.
- _How should the reviewer approach this PR, especially if manual tests are required?_
I have a GitLab self-hosted instance …
=> Add support for authn-jwt with JWT token

CHANGELOG.md, bin/dev.sh, bin/start-conjur.sh, bin/test.sh, conjurapi/client.go, conjurapi/resource.go, conjurapi/resource_test.go
This pull request implements the API side of adding the role parameter into the 'check' command for the Go CLI.
- Updated API endpoint for 'check'
- Updated tests for API endpoint
merged.*
changes, or
=> Implements role parameter in check command in API

CHANGELOG.md, CONTRIBUTING.md, Dockerfile, Jenkinsfile, NOTICES.txt, README.md, bin/test.sh, docker-compose.yml, go.mod, go.sum
* Upgrade yaml.v3 indirect versions to 3.0.1 (via replace statement)
* Upgrade dockerfile to golang:1.19
* Add 1.19 testing to pipeline
merged.*
changes, or
=> Upgrade yaml.v3 indirect dependency and Dockerfile to golang:1.19.5

conjurapi/authn.go, conjurapi/authn_test.go
Create a change password command that pulls current user credentials using the API instead of requiring the user to provide them.
=> Add method to change password for logged-in user

CHANGELOG.md, conjurapi/host_factory.go, conjurapi/host_factory_test.go
Hostfactory should not require the  fully qualified host factory id
This inserts the account and host_factory portion of the host factory id
CyberArk internal issue ID: [insert issue ID]
merged.*
changes, or
=> Fixes issue with hostfactory requiring the fully qualified host factory id

CHANGELOG.md, conjurapi/authn.go, conjurapi/authn_test.go, conjurapi/client.go
Allow fully-qualified IDs to be passed to `client.RotateUserAPIKey()` and `client.RotateHostAPIKey()`.
API Key rotation functions use new `client.parseIDandEnforceKind(resourceID, kind string)` function to accept and parse both fully- and partially-qualified role IDs while enforcing a kind requirement.
Resolves #[relevant GitHub issue(s), e.g. 76]
CyberArk internal issue ID: [insert issue ID]
merged.*
changes, or
=> Functions for API key rotation now support fully-qualified IDs

conjurapi/resource_test.go, conjurapi/role_test.go
Fix conjur-api-go builds, which are currently failing in unit tests due to recent updates to Conjur. The cause is likely this PR: https://github.com/cyberark/conjur/pull/2757 which adds a resource for the admin user, which in turn is affecting some tests which use hard-coded resource/role counts as an expectation.
Update failing unit tests to account for this recent change
merged.*
changes, or
=> Update tests to account for admin user resource

conjurapi/client.go, conjurapi/client_test.go, conjurapi/config.go, conjurapi/config_test.go
The aim is to be able to set the http client timeout, which is currently set to 10 seconds in the code.
The modification consists in adding the "HttpTimeout" integer to the "Config" structure and using it when instantiating the "http.Client" object.
- This PR includes new unit and integration tests to go with the code
changes
=> add ability to set http timeout
